elasticsearch:
  image: elasticsearch
  esJavaOpts: -Xmx8g -Xms8g
  replicas: 3
  resources:
    limits:
      memory: 10Gi
    requests:
      memory: 10Gi
  sysctlInitContainer:
    enabled: false
  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 30Gi
  discoverable:
    allow: true

kibana:
  image: kibana

ingress:
  enabled: true
  tls: true
  ingressClassName: ""  
  annotations: []
    # kubernetes.io/tls-acme: "true"
  hostname: chart-example.local
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

route:
  enabled: false
  annotations: []
    # route.openshift.io/termination: "reencrypt"
  hostname: chart-example.local
  tls:
    termination: edge
    # key:
    # certificate:
    # caCertificate:
    # destinationCACertificate:
  wildcardPolicy: None

security:
  allowlist:
    enabled: true
    ip: "0.0.0.0/0" 
  networkPolicy: 
    enabled: true
    from: []
