{{- if .Values.kafka.discoverable.allow }}
{{- $fullname := include "common.names.fullname" . }}
{{- $secretName := printf "%s-%s" "discoverable" $fullname -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  annotations:
    onyxia/discovery: "kafka"
type: Opaque
data:
  kafka-service: {{ (include "kafkaList" .)  | b64enc | quote }}
{{- end -}}