apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "library-chart.fullname" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
data:
  {{- if .Values.postgresql.extensions.postgis }}
  enable-extensions.sh: |
    #!/bin/sh
    export PGPASSWORD=$POSTGRES_PASSWORD
    psql -U postgres -d $POSTGRES_DB -c "CREATE EXTENSION postgis;"
    psql -U postgres -d $POSTGRES_DB -c "CREATE EXTENSION postgis_topology;"
  {{ else }}
  enable-extensions.sh: |
    #!/bin/sh
    echo "No additional extensions created."
  {{- end -}}