{{- if .Values.discoverable.allow }}
{{- $fullname := (include "library-chart.fullname" .) -}}
{{- $secretName := printf "%s-%s" "discoverable" $fullname -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  annotations:
    onyxia/discovery: "hive"
type: Opaque
data:
  hive-service: {{ (include "library-chart.fullname" .) | b64enc | quote }}
  hive-endpoint: {{ .Values.s3.endpoint | default ".Values.s3.endpoint"  | b64enc | quote }}
{{- end -}}