apiVersion: v1
entries:
  mysql:
  - annotations:
      category: Database
      images: |
        - name: mysql
          image: docker.io/bitnami/mysql:8.0.35-debian-11-r2
        - name: mysqld-exporter
          image: docker.io/bitnami/mysqld-exporter:0.15.1-debian-11-r0
        - name: os-shell
          image: docker.io/bitnami/os-shell:11-debian-11-r93
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 8.0.35
    created: "2024-01-11T13:34:52.749676815Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: MySQL is a fast, reliable, scalable, and easy to use open source
      relational database system. Designed to handle mission-critical, heavy-load
      production applications.
    digest: 850788104de3bb58c1cb8b4fc52937c8846324ed586b2bd6276c65e6f74ed340
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/mysql/img/mysql-stack-220x234.png
    keywords:
    - mysql
    - database
    - sql
    - cluster
    - high availability
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: mysql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mysql
    urls:
    - https://github.com/ChatBear/images_docker-/releases/download/mysql-9.16.1/mysql-9.16.1.tgz
    version: 9.16.1
generated: "2024-01-11T13:34:52.749686854Z"