{{- if .Values.discoverable.allow }}
{{- $fullname := include "common.names.fullname" . }}
{{- $secretName := printf "%s-%s" "discoverable" $fullname -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  annotations:
    onyxia/discovery: "postgres"
type: Opaque
data:
  postgres-service: {{ (include "common.names.fullname" .) | b64enc | quote }}
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | default ".Values.postgresql.auth.postgresPassword"  | b64enc | quote }}
  password: {{ .Values.postgresql.auth.password | default ".Values.postgresql.auth.password"  | b64enc | quote }}
  postgres-username: {{ .Values.postgresql.auth.username | default ".Values.postgresql.auth.username"  | b64enc | quote }}
  postgres-database: {{ .Values.postgresql.auth.database | default ".Values.postgresql.auth.database" | b64enc | quote }}
  postgres-port: {{ .Values.postgresql.containerPorts.postgresql | quote }}
{{- end -}}
