{{- if .Values.elasticsearch.discoverable.allow }}
{{- $fullname := .Chart.Name | default "elasticOverrideFullname" }}
{{- $secretName := printf "%s-%s" "discoverable" $fullname -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  annotations:
    onyxia/discovery: "elastic"
type: Opaque
data:
  elastic-service: {{ "elasticsearch-master" | b64enc | quote }}
  elastic-port: {{ .Values.elasticsearch.httpPort | toString | default ".Values.elasticsearch.httpPort"  | b64enc | quote }}
  elastic-name: {{ printf "%s" $fullname  | b64enc | quote }}
{{- end -}}