{{- if .Values.discoverable.allow }}
{{- $fullname := include "common.names.fullname" . }}
{{- $secretName := printf "%s-%s" "discoverable" $fullname -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  annotations:
    onyxia/discovery: "mariadb"
type: Opaque
data:
  mariadb-service: {{ (include "common.names.fullname" .) | b64enc | quote }}
  mariadb-password: {{ .Values.mariadb.auth.rootPassword | default ".Values.mariadb.auth.rootPassword"  | b64enc | quote }}
  password: {{ .Values.mariadb.auth.password | default ".Values.mariadb.auth.password"  | b64enc | quote }}
  mariadb-username: {{ .Values.mariadb.auth.username | default ".Values.mariadb.auth.username"  | b64enc | quote }}
  mariadb-database: {{ .Values.mariadb.auth.database | default ".Values.mariadb.auth.database" | b64enc | quote }}
  mariadb-port: {{ .Values.mariadb.primary.service.ports.mysql | quote }}
{{- end -}}
