{{- if .Values.discovery.postgres -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "library-chart.fullname" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
data:
  servers.json: |-
    {{- include "pgadmin.configmap" . | nindent 4 }}
{{- end }}
