apiVersion: v1
kind: Service
metadata:
  name: {{ include "library-chart.fullname" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.type }}
  ports:
    - port: {{ .Values.networking.neo4jUI.port }}
      targetPort: ui
      protocol: TCP
      name: ui
    - port: {{ .Values.networking.neo4jBolt.port }}
      targetPort: bolt
      protocol: TCP
      name: bolt
  selector:
    {{- include "library-chart.selectorLabels" . | nindent 4 }}
