{{- if .Values.discoverable.allow }}
{{- $fullname := include "library-chart.fullname" . -}}
{{- $secretName := printf "%s-%s" "discoverable" $fullname -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  annotations:
    onyxia/discovery: "spark-thrift-server"
type: Opaque
data:
  thrift-service: {{ printf "%s" $fullname | b64enc | quote }}
  thrift-port: {{ print .Values.networking.port | b64enc | quote }}
{{- end -}}
